# Inegi

**References**

* [Inegi](https://www.inegi.org.mx/servicios/api_indicadores.html)
* [Script](https://pablocruz.io/inflation-api-python/)
* [Youtube](https://www.youtube.com/watch?v=ps57X1aJGgo)
* [Web](https://escueladedatos.online/tutorial/como-consultar-una-api-desde-excel/)

In [1]:
import locale
import requests
import json
import pandas as pd
from bs4 import BeautifulSoup
import time

In [2]:
# path to credentials folder
filename = '../APIS/credentials.json'

# read json file
with open(filename) as f:
    keys = json.load(f)

# read credentials
token = keys['inegi_api']

In [3]:
inegi = f'https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/1002000026/es/0700/false/BISE/2.0/{inegi_id}?type=json'

NameError: name 'inegi_id' is not defined

In [4]:
inegi

NameError: name 'inegi' is not defined

In [5]:
pop = '1002000026'
query = 'false'

url = (
        'https://www.inegi.org.mx/app/api/indicadores/'
        + 'desarrolladores/jsonxml/INDICATOR/'
        + pop
        + '/es/0700/'
        + query
        + '/BISE/2.0/'
        + token
#        + '?type=json'
)

In [6]:
# Se pasa como un request con metodo get
response = requests.get(url)
# Se le solicita el codigo de respuesta al servidor.    
status = response.status_code

In [7]:
# Guarda la respuesta como una variable
content = response.json()
# Se filtra el json
data = content["Series"][0]["OBSERVATIONS"]
# Se accesa el diccionario con los datos
# pandas dataframe
df = pd.DataFrame(data)

In [8]:
df

,TIME_PERIOD,OBS_VALUE,OBS_EXCEPTION,OBS_STATUS,OBS_SOURCE,OBS_NOTE,COBER_GEO
0,1994,2904389.00000000000000000000,None,3,,,0700
1,1995,2750444.00000000000000000000,None,3,,,0700
2,1996,2707718.00000000000000000000,None,3,,,0700
3,1997,2698425.00000000000000000000,None,3,,,0700
4,1998,2668428.00000000000000000000,None,3,,,0700
5,1999,2769089.00000000000000000000,None,3,,,0700
6,2000,2798339.00000000000000000000,None,3,,,0700
7,2001,2767610.00000000000000000000,None,3,,,0700
8,2002,2699084.00000000000000000000,None,3,,,0700
9,2003,2655894.00000000000000000000,None,3,,,0700
10,2004,2625056.00000000000000000000,None,3,,,0700
11,2005,2567906.00000000000000000000,None,3,,,0700
12,2006,2505939.00000000000000000000,None,3,,,0700
13,2007,2655083.00000000000000000000,None,3,,,0700
14,2008,2636110.00000000000000000000,None,3,,,0700
15,2009,2577214.00000000000000000000,None,3,,,0700
16,2010,2643908.00000000000000000000,None,3,,,0700
17,2011,2586287.00000000000000000000,None,3,,,0700
18,2012,2498880.00000000000000000000,None,3,,,0700
19,2013,2478889.00000000000000000000,None,3,,9379,0700
20,2014,2463420.00000000000000000000,None,3,,9380,0700
21,2015,2353596.00000000000000000000,None,3,,,0700
22,2016,2293708.00000000000000000000,None,3,,8391,0700
23,2017,2234039.00000000000000000000,None,3,,9105,0700
24,2018,2162535.00000000000000000000,None,3,,11066,0700
25,2019,2092214.00000000000000000000,None,3,,10556,0700
26,2020,1629211.00000000000000000000,None,3,,,0700
27,2021,1912178.00000000000000000000,None,3,,,0700
28,2022,1891388.00000000000000000000,None,3,,11239,0700

In [9]:
response = requests.get(inegi)
data = json.loads(response.text)
data.keys()
df = pd.DataFrame(data['Series'])
df.explode(list('OBSERVATIONS'))

NameError: name 'inegi' is not defined

In [10]:
catalog = pd.read_csv('https://www.inegi.org.mx/rnm/index.php/catalog/export/csv?ps=5000&collection[]=')
catalog['changed'] = pd.to_datetime(catalog['changed'])
catalog = catalog.set_index('id')

/var/folders/jy/hhl49vr95cdgq4r9c_fgwhd80000gn/T/ipykernel_36443/1409676539.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  catalog['changed'] = pd.to_datetime(catalog['changed'])

In [11]:
catalog

,idno,title,nation,authoring_entity,year_start,year_end,created,changed
id,,,,,,,,
847,MEX-INEGI.EEC3.01-EMIM-2023,Encuesta Mensual de la Industria Manufacturera...,Mexico,"Instituto Nacional de Estadística y Geografía,...",2023,2023,Mar-13-23,2023-10-12
838,MEX-INEGI-EEC3.01-EMOE-2023,"Encuesta Mensual de Opinión Empresarial 2023, ...",Mexico,"Instituto Nacional de Estadística y Geografía,...",2023,2023,Jan-30-23,2023-10-31
853,MEX-INEGI.EEC3.02-EMEC-2023,Encuesta Mensual sobre Empresas Comerciales 20...,Mexico,"Instituto Nacional de Estadística y Geografía,...",2023,2023,Mar-17-23,2023-10-19
851,MEX-INEGI.EEC3.01-ENEC-2023,Encuesta Nacional de Empresas Constructoras 20...,Mexico,"Instituto Nacional de Estadística y Geografía,...",2023,2023,Mar-17-23,2023-10-20
866,MEX-INEGI.ESD3.03-ENOE-2023-I,"Encuesta Nacional de Ocupación y Empleo 2023, ...",Mexico,"Instituto Nacional de Estadística y Geografía,...",2023,2023,May-26-23,2023-08-24
...,...,...,...,...,...,...,...,...
278,MEX-INEGI.ESD3.06-EVMAT-1993-2001,Estadísticas Vitales. Matrimonios 1993-2001,Mexico,Instituto Nacional de Estadística y Geografía ...,1993,2001,Aug-07-17,2022-08-03
295,MEX-INEGI.EST.40.202.05-DERL-1991-2016,Estadísticas sobre Relaciones Laborales de Jur...,Mexico,"Instituto Nacional de Estadística y Geografía,...",1991,2016,Nov-01-17,2022-10-07
382,MEX-INEGI.302.03-VMRC-1991-2016,"Vehículos de Motor Registrados en Circulación,...",Mexico,"Instituto Nacional de Estadística y Geografía,...",1991,2017,Sep-12-18,2022-09-07
267,MEX-INEGI.ESD3.06-EVDIV-1985-2001,Estadísticas Vitales. Divorcios 1985-2001,Mexico,"Instituto Nacional de Estadística y Geografía,...",1985,2002,Jul-17-17,2023-01-26
296,MEX-INEGI.40.202.06-EVNAC-1985-2001,Estadísticas Vitales. Natalidad 1985-2001,Mexico,"Instituto Nacional de Estadística y Geografía,...",1985,2001,Nov-01-17,2022-10-05

In [12]:
sep2023 = catalog.loc[catalog['changed'].between('2023-09-01', '2023-09-14')]
sep2023.head()

,idno,title,nation,authoring_entity,year_start,year_end,created,changed
id,,,,,,,,
907,MEX-INEGI.ESD3.03-ENOE-2023-II,"Encuesta Nacional de Ocupación y Empleo 2023, ...",Mexico,"Instituto Nacional de Estadística y Geografía,...",2023,2023,Aug-24-23,2023-09-08
881,MEX-INEGI.40.1200.03-CNIJF-2023,Censo Nacional de Impartición de Justicia Fede...,Mexico,Instituto Nacional de Estadística y Geografía ...,2022,2023,Jul-10-23,2023-09-11
882,MEX-INEGI.EEC6.03-EFIPEM-2022,Estadística de Finanzas Públicas Estatales y M...,Mexico,"Instituto Nacional de Estadística y Geografía,...",2022,2023,Jul-11-23,2023-09-06

In [13]:
url = 'https://www.inegi.org.mx/rnm/index.php/catalog/'

for id in sep2023.index:
    response = requests.get(url + str(id) + '/related-materials')
    print('Response code: ', response.status_code)
    soup = BeautifulSoup(response.text, 'html.parser')
    links = soup.find_all('a', class_ = 'download btn btn-outline-primary btn-sm btn-block')
    time.sleep(3)

Response code:  200
Response code:  200
Response code:  200

## Contact

<!-- Avatar -->
<img src="../Pictures/profile2.png" alt="me" width="75" height="80">
<!-- Text with color, font, fontsize and specific size -->
<p style="color:#323232; font-family: Helevetica; font-size: 20px;">Jesus L. Monroy<br>Economist | Data Scientist</p>
<!-- Insert url links in logos -->
<!-- Telegram -->
<a href="https://t.me/j3suslm" target="_blank" rel="noreferrer"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Telegram_X_2019_Logo.svg/2048px-Telegram_X_2019_Logo.png?size=16&color=3b3b3b" alt="telegram" width="30" height="22" style="padding-left:8px"/>
<!-- Twitter -->
<a href="https://www.twitter.com/sqlalchemist" target="_blank" rel="noreferrer"> <img src="https://toppng.com/public/uploads/preview/twitter-x-new-logo-round-icon-png-11692480241tdbz6jparr.webp?size=16&color=3b3b3b" alt="twitter" width="30" height="22" style="padding-left:8px"/>
<!-- Github -->
<a href="https://github.com/SqlAlchemist/My-portfolio" target="_blank" rel="noreferrer"> <img src="https://icongr.am/devicon/github-original.svg?size=16&color=3b3b3b" alt="github" width="30" height="30" style="padding-left:8px"/>
<!-- Linkedin -->
<a href="https://www.linkedin.com/in/j3sus-lmonroy" target="_blank" rel="noreferrer"> <img src="https://icongr.am/simple/linkedin.svg?size=16&color=3b3b3b" alt="linkedin" width="30" height="30" style="padding-left:8px"/>
<!-- Medium -->
<a href="https://medium.com/@jesus_lmonroy" target="_blank" rel="noreferrer"> <img src="https://cdn1.iconfinder.com/data/icons/social-media-and-logos-12/32/Logo_medium-512.png?size=55&color=3b3b3b" alt="medium" width="30" height="33" style="padding-left:8px"/>